---
title: "01-volume_model_calc"
output: html_document
date: "2026-07-01"
---
## Load libraries
```{r}
library(readxl)
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(modelr)
```

# Load manual measurement data
```{r}
# B survival
B_growth <- read_xlsx("data/sizes/B_2023POGS_small_seed_daily/B_sizes_08202025.xlsx")

# Heights from bag 2 for 07/05/2024 showing up as NAs for some reason when data imported
B_growth$length.mm <- as.numeric(B_growth$length.mm)
B_growth$width.mm <- as.numeric(B_growth$width.mm)
B_growth$height.mm <- as.numeric(B_growth$height.mm)
B_growth$date <- as.Date(B_growth$date)

B_growth <- B_growth %>% drop_na(length.mm, width.mm, height.mm)

# D survival
D_growth <- read_xlsx("data/sizes/D_2023POGS_small_seed_weekly/D_sizes_08202025.xlsx", guess_max = 2000)
D_growth <- D_growth %>% drop_na(length.mm, width.mm, height.mm)
D_growth$length.mm <- as.numeric(D_growth$length.mm)
D_growth$width.mm <- as.numeric(D_growth$width.mm)
D_growth$height.mm <- as.numeric(D_growth$height.mm)
D_growth$date <- as.Date(D_growth$date)
```


## Calculate volume
```{r}
growth_model <- rbind(B_growth,D_growth)
growth_model$date_numeric <- as.numeric(as.Date(growth_model$date))
growth_model$tag_num <- as.factor(growth_model$tag_num)
growth_model$bag_num <- as.factor(growth_model$bag_num)

 growth_model$volume <- (4/3) * pi * (growth_model$length.mm/2) * (growth_model$width.mm/2) * (growth_model$height.mm) * (1/2)

growth_model$conditioning <- gsub("weekly", "treated", growth_model$conditioning)
growth_model$conditioning <- gsub("daily", "treated", growth_model$conditioning)

```


#Non linear volume model
```{r}
# Non Linear model predicting log volume from length 
model <- nls(log(volume) ~ a*length.mm^b, data = growth_model, start = list(a = 6.8, b = 1.1))
summary(model)
modelr::rsquare(model, growth_model)
plot(model)

# Extracting coefficients 
coef_est <- coef(model)
cov_matrix <- vcov(model)

# Calculate standard errors for predictions
growth_model$predicted <- predict(model)
se_pred <- numeric(length(growth_model$predicted))
for (i in 1:length(growth_model$predicted)) {
  x_val <- growth_model$length.mm[i]
  # Jacobian for the prediction
  jacobian <- c(x_val^coef_est["b"], coef_est["a"] * log(x_val) * x_val^coef_est["b"])
  se_pred[i] <- sqrt(t(jacobian) %*% cov_matrix %*% jacobian)
}

# Calculate the confidence intervals
alpha <- 0.05  # significance level for 95% CI
z_value <- qnorm(1 - alpha / 2)  # Z value for the normal distribution

# Compute confidence intervals
growth_model$lower_ci <- growth_model$predicted - z_value * se_pred
growth_model$upper_ci <- growth_model$predicted + z_value * se_pred

# Graph Length to log volume with model line
ggplot(growth_model, aes(x = length.mm, y = volume, color = date)) +
  geom_point() +  
  geom_line(aes(y = exp(predicted)), color = "red", linewidth = 1) + 
  labs(x = "length",
       y = "volume") +
  theme_classic()

# Graph actual log volume versus predicted log volume 
ggplot(growth_model, aes(x = log(volume), y = predicted)) +
  geom_point(color = "blue", size = 2) +
  labs(x = "Log volume",
       y = "Predicted log volume") +
  geom_smooth(method='lm', color = "red")+
  theme_classic()+
  ylim(5,13)+
  xlim(5,13)
```



