---
title: "Downloading apex data"
output: html_document
date: "2024-06-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Must run this script when on the same WiFi as the Apex unit.  

Author: HM Putnam 
Edited by: AS Huffmyer
Date Last Modified: 20240612

```{r}
library("XML")
library("plyr")
library("lubridate")
```
Downloads 30 days at a time. 

March to April 
```{r}
xmlfile <- xmlParse("http://192.168.10.131/cgi-bin/datalog.xml?sdate=240301&days=103") #read in the date (e.g. 240301) plus # days (e.g. days=103) of Apex data
parsed <- ldply(xmlToList(xmlfile), data.frame) #convert xml to dataframe
```

```{r}
write.csv(parsed, "data/environmental/apex/indoor_tanks_20240301_20240401.csv") #write file to save data
```

January to February
```{r}
xmlfile2 <- xmlParse("http://192.168.10.131/cgi-bin/datalog.xml?sdate=240101&days=90") #read in the date (e.g. 240301) plus # days (e.g. days=103) of Apex data
parsed2 <- ldply(xmlToList(xmlfile2), data.frame) #convert xml to dataframe
```

```{r}
write.csv(parsed2, "data/environmental/apex/indoor_tanks_20240101_20240201.csv") #write file to save data
```

February to March
```{r}
xmlfile3 <- xmlParse("http://192.168.10.131/cgi-bin/datalog.xml?sdate=240201&days=30") #read in the date (e.g. 240301) plus # days (e.g. days=103) of Apex data
parsed3 <- ldply(xmlToList(xmlfile3), data.frame) #convert xml to dataframe
```

```{r}
write.csv(parsed3, "data/environmental/apex/indoor_tanks_20240201_20240301.csv") #write file to save data
```

April to May
```{r}
xmlfile4 <- xmlParse("http://192.168.10.131/cgi-bin/datalog.xml?sdate=240401&days=30") #read in the date (e.g. 240301) plus # days (e.g. days=103) of Apex data
parsed4 <- ldply(xmlToList(xmlfile4), data.frame) #convert xml to dataframe
```

```{r}
write.csv(parsed4, "data/environmental/apex/indoor_tanks_20240401_20240501.csv") #write file to save data
```

May to June

```{r}
xmlfile5 <- xmlParse("http://192.168.10.131/cgi-bin/datalog.xml?sdate=240501&days=30") #read in the date (e.g. 240301) plus # days (e.g. days=103) of Apex data
parsed5 <- ldply(xmlToList(xmlfile5), data.frame) #convert xml to dataframe
```

```{r}
write.csv(parsed5, "data/environmental/apex/indoor_tanks_20240501_20240601.csv") #write file to save data
```

