---
title: "growth_imageJ_Westcott"
output: html_document
date: "2025-01-08"
---

### Load libraries
```{r}
library(readxl)
library(tidyverse)
library(ggplot2)
library(gridExtra)


```

```{r}
growth_IJ <- read_xlsx("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/project-gigas-conditioning-GL/data/outplanting/Westcott/20241217_images/sizes_12172024.xlsx")
```


```{r}
means_sizes <- growth_IJ %>%
  group_by(effort, conditioning, date, metric) %>%
  summarise(mean_length = mean(measure.mm, na.rm = TRUE),
            stderr_length = sd(measure.mm, na.rm = TRUE)/sqrt(length(measure.mm)),
            .groups = 'drop')
```

```{r}
growth_IJ <- growth_IJ %>%
  pivot_wider(names_from = metric, values_from = measure.mm)

```

```{r}
### Run morph relationships code first to get the non linear model set up

names(growth_IJ)[names(growth_IJ) == 'length'] <- 'length.mm'
growth_IJ$pred_log_vol <- predict(model, newdata= growth_IJ) 
growth_IJ$pred_vol <- exp(growth_IJ$pred_log_vol)

ggplot(growth_IJ, aes(x = length.mm, y = pred_log_vol)) +
  geom_point(color = "blue", size = 2) +  
  labs(x = "length",
       y = "volume") +
  theme_classic()


```

```{r}
plot(growth$length.mm, growth$volume) 
  
# overlay line plot  
points(growth_IJ$length.mm, growth_IJ$pred_vol, col = "green")
```

### Combine growth volumes with December ImageJ volumes to see if predicted volumes match up well

```{r}

names(growth_IJ)[names(growth_IJ) == 'width'] <- 'width.mm'
names(growth_IJ)[names(growth_IJ) == 'pred_vol'] <- 'volume'

growth_IJ_sym <- growth_IJ %>% select(-c(oyster, pred_log_vol))
growth_sym <- growth %>% select(-c(bag_num, height.mm, duplicate, tag_num, notes,date_numeric, predicted, lower_ci, upper_ci))

growth_with_IJ <- rbind(growth_sym, growth_IJ_sym)
```


### Predicted volumes underestimate vol 
```{r}
ggplot(growth_with_IJ, aes(x=length.mm, y=volume, col = date))+
  geom_point()+
  theme_classic()+
  labs(x= "Length (mm)", y = expression(paste("Volume ", (mm^{3}))), col = "Date")
  
```

