---
title: "growth_GL"
output: html_document
date: "2024-07-09"
---

### Load libraries
```{r}
library(readxl)
library(tidyverse)
library(ggplot2)
library(gridExtra)

```

### Load Data
```{r}
# B survival
B_growth <- read_xlsx("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/project-gigas-conditioning-GL/data/sizes/B_2023POGS_small_seed_daily/B_sizes_09132024.xlsx")

# Heights from bag 2 for 07/05/2024 showing up as NA's for some reason when data imported
B_growth$length.mm <- as.numeric(B_growth$length.mm)
B_growth$width.mm <- as.numeric(B_growth$width.mm)
B_growth$height.mm <- as.numeric(B_growth$height.mm)

B_growth <- B_growth %>% drop_na(length.mm, width.mm, height.mm)

# D survival
D_growth <- read_xlsx("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/project-gigas-conditioning-GL/data/sizes/D_2023POGS_small_seed_weekly/D_sizes_09132024.xlsx")
D_growth <- D_growth %>% drop_na(length.mm, width.mm, height.mm)

```

```{r}
ggplot(B_growth, aes(x=length.mm, y= height.mm))+
  geom_point()+
  theme_classic()
```
```{r}
ggplot(D_growth, aes(x=length.mm, y= height.mm))+
  geom_point()+
  theme_classic()
```




### Means with NT's included
```{r}
means_B_sizes <- B_growth %>%
  group_by(conditioning, date) %>%
  summarise(mean_length = mean(length.mm, na.rm = TRUE),
            mean_width = mean(width.mm, na.rm = TRUE),
            mean_height = mean(height.mm, na.rm = TRUE), 
            stderr_length = sd(length.mm, na.rm = TRUE)/sqrt(length(length.mm)),
            stderr_width = sd(width.mm, na.rm = TRUE)/sqrt(length(width.mm)),
            stderr_height = sd(height.mm, na.rm = TRUE)/sqrt(length(height.mm)),
            .groups = 'drop')

means_D_sizes <- D_growth %>%
  group_by(conditioning, date) %>%
  summarise(mean_length = mean(length.mm, na.rm = TRUE),
            mean_width = mean(width.mm, na.rm = TRUE),
            mean_height = mean(height.mm, na.rm = TRUE), 
            stderr_length = sd(length.mm, na.rm = TRUE)/sqrt(length(length.mm)),
            stderr_width = sd(width.mm, na.rm = TRUE)/sqrt(length(width.mm)),
            stderr_height = sd(height.mm, na.rm = TRUE)/sqrt(length(height.mm)),
            .groups = 'drop')


```


### Graphs with NT's included
```{r}

DL <- ggplot(means_D_sizes, aes(x = date, y = mean_length, color = conditioning)) +
   geom_point() +
  labs(x = "Date",
       y = "Mean length (mm)") +
  theme_classic()+
  scale_color_manual(labels = c("Control", "Weekly"), values = c("green","purple"))+
  geom_errorbar(aes(ymin=mean_length-stderr_length, ymax = mean_length+stderr_length), width=.2,
                 position=position_dodge(0.05))+
  theme(
    axis.title.x = element_blank(),       
    axis.text.x = element_blank())+
  ylim(0,50)

DW <- ggplot(means_D_sizes, aes(x = date, y = mean_width, color = conditioning)) +
   geom_point() +
  labs(x = "Date",
       y = "Mean width (mm)") +
  theme_classic()+
  scale_color_manual(labels = c("Control", "Weekly"), values = c("green","purple"))+
  labs(color = "Conditioning")+
  geom_errorbar(aes(ymin=mean_width-stderr_width, ymax = mean_width+stderr_width), width=.2,
                 position=position_dodge(0.05))+
  theme(
    axis.title.x = element_blank(),       
    axis.text.x = element_blank())+
  ylim(0,50)

DH <- ggplot(means_D_sizes, aes(x = date, y = mean_height, color = conditioning)) +
   geom_point() +
  labs(x = "Date",
       y = "Mean height (mm)") +
  theme_classic()+
  geom_errorbar(aes(ymin=mean_height-stderr_height, ymax = mean_height+stderr_height), width=.2,
                 position=position_dodge(0.05))+
  scale_color_manual(labels = c("Control", "Weekly"), values = c("green","purple"))+
  ylim(0,50)

grid.arrange(DL,DW,DH)


```



```{r}
BL <- ggplot(means_B_sizes, aes(x = date, y = mean_length, color = conditioning)) +
   geom_point(size=3) +
  labs(x = "Date",
       y = "Mean length (mm)") +
  scale_color_manual(labels = c("Control", "Daily"), values = c("blue","red"))+
  theme_classic()+
  geom_errorbar(aes(ymin=mean_length-stderr_length, ymax = mean_length+stderr_length), width=.2,
                 position=position_dodge(0.05))+
  theme(
    axis.title.x = element_blank(),       
    axis.text.x = element_blank())+
  ylim(0,50)

BW <- ggplot(means_B_sizes, aes(x = date, y = mean_width, color = conditioning)) +
   geom_point(size=3) +
  scale_color_manual(labels = c("Control", "Daily"), values = c("blue","red"))+
  labs(color = "Conditioning")+
  labs(x = "Date",
       y = "Mean width (mm)") +
  geom_errorbar(aes(ymin=mean_width-stderr_width, ymax = mean_width+stderr_width), width=.2,
                 position=position_dodge(0.05))+
  theme_classic()+
  theme(
    axis.title.x = element_blank(),       
    axis.text.x = element_blank())+
  ylim(0,50)

BH <- ggplot(means_B_sizes, aes(x = date, y = mean_height, color = conditioning)) +
   geom_point(size=3) +
  scale_color_manual(labels = c("Control", "Daily"), values = c("blue","red"))+
  labs(x = "Date",
       y = "Mean height (mm)") +
  geom_errorbar(aes(ymin=mean_height-stderr_height, ymax = mean_height+stderr_height), width=.2,
                 position=position_dodge(0.05))+
  theme_classic()+
  ylim(0,50)

grid.arrange(BL,BW,BH)
```

### Means with NT's excluded

```{r}
B_noNT <- B_growth[B_growth$tag_num != "NT", ]
D_noNT <- D_growth[D_growth$tag_num != "NT", ]
```


```{r}
means_B_sizes_noNT <- B_noNT %>%
  group_by(conditioning, date) %>%
  summarise(mean_length = mean(length.mm, na.rm = TRUE),
            mean_width = mean(width.mm, na.rm = TRUE),
            mean_height = mean(height.mm, na.rm = TRUE), 
            stderr_length = sd(length.mm, na.rm = TRUE)/sqrt(length(length.mm)),
            stderr_width = sd(width.mm, na.rm = TRUE)/sqrt(length(width.mm)),
            stderr_height = sd(height.mm, na.rm = TRUE)/sqrt(length(height.mm)),
            .groups = 'drop')

means_D_sizes_noNT <- D_noNT %>%
  group_by(conditioning, date) %>%
  summarise(mean_length = mean(length.mm, na.rm = TRUE),
            mean_width = mean(width.mm, na.rm = TRUE),
            mean_height = mean(height.mm, na.rm = TRUE), 
            stderr_length = sd(length.mm, na.rm = TRUE)/sqrt(length(length.mm)),
            stderr_width = sd(width.mm, na.rm = TRUE)/sqrt(length(width.mm)),
            stderr_height = sd(height.mm, na.rm = TRUE)/sqrt(length(height.mm)),
            .groups = 'drop')
```

### Graphs with NT's excluded
```{r}

DL2 <- ggplot(means_D_sizes_noNT, aes(x = date, y = mean_length, color = conditioning)) +
   geom_point() +
  labs(x = "Date",
       y = "Mean length (mm)") +
  labs(color = "Conditioning")+
  theme_classic()+
  scale_color_manual(labels = c("Control", "Weekly"), values = c("green","purple"))+
  geom_errorbar(aes(ymin=mean_length-stderr_length, ymax = mean_length+stderr_length), width=.2,
                 position=position_dodge(0.05))+
  theme(
    axis.title.x = element_blank(),       
    axis.text.x = element_blank())+
  ylim(0,50)

DW2 <- ggplot(means_D_sizes_noNT, aes(x = date, y = mean_width, color = conditioning)) +
   geom_point() +
  labs(x = "Date",
       y = "Mean width (mm)") +
  theme_classic()+
  scale_color_manual(labels = c("Control", "Weekly"), values = c("green","purple"))+
  labs(color = "Conditioning")+
  geom_errorbar(aes(ymin=mean_width-stderr_width, ymax = mean_width+stderr_width), width=.2,
                 position=position_dodge(0.05))+
  theme(
    axis.title.x = element_blank(),       
    axis.text.x = element_blank())+
  ylim(0,50)

DH2 <- ggplot(means_D_sizes_noNT, aes(x = date, y = mean_height, color = conditioning)) +
   geom_point() +
  labs(x = "Date",
       y = "Mean height (mm)") +
  labs(color = "Conditioning")+
  theme_classic()+
  geom_errorbar(aes(ymin=mean_height-stderr_height, ymax = mean_height+stderr_height), width=.2,
                 position=position_dodge(0.05))+
  scale_color_manual(labels = c("Control", "Weekly"), values = c("green","purple"))+
  ylim(0,20)

grid.arrange(DL2,DW2,DH2)

```






```{r}
BL2 <- ggplot(means_B_sizes_noNT, aes(x = date, y = mean_length, color = conditioning)) +
   geom_point(size=3) +
  labs(x = "Date",
       y = "Mean length (mm)") +
  scale_color_manual(labels = c("Control", "Daily"), values = c("blue","red"))+
  theme_classic()+
  geom_errorbar(aes(ymin=mean_length-stderr_length, ymax = mean_length+stderr_length), width=.2,
                 position=position_dodge(0.05))+
  labs(color = "Conditioning")+
  theme(
    axis.title.x = element_blank(),       
    axis.text.x = element_blank())+
  ylim(0,45)

BW2 <- ggplot(means_B_sizes_noNT, aes(x = date, y = mean_width, color = conditioning)) +
   geom_point(size=3) +
  scale_color_manual(labels = c("Control", "Daily"), values = c("blue","red"))+
  labs(color = "Conditioning")+
  labs(x = "Date",
       y = "Mean width (mm)") +
  geom_errorbar(aes(ymin=mean_width-stderr_width, ymax = mean_width+stderr_width), width=.2,
                 position=position_dodge(0.05))+
  theme_classic()+
  theme(
    axis.title.x = element_blank(),       
    axis.text.x = element_blank())+
  ylim(0,45)

BH2 <- ggplot(means_B_sizes_noNT, aes(x = date, y = mean_height, color = conditioning)) +
   geom_point(size=3) +
  scale_color_manual(labels = c("Control", "Daily"), values = c("blue","red"))+
  labs(x = "Date",
       y = "Mean height (mm)") +
  labs(color = "Conditioning")+
  geom_errorbar(aes(ymin=mean_height-stderr_height, ymax = mean_height+stderr_height), width=.2,
                 position=position_dodge(0.05))+
  theme_classic()+
  ylim(0,20)

grid.arrange(BL2,BW2,BH2)
```






