---
title: "Morph_relationships"
output: html_document
date: "2024-10-03"
---

### Load libraries
```{r}
library(readxl)
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(lmtest)
library(car)
install.packages("lmerTest")
library(lmerTest)
```

### Load Data
```{r}
# B survival
B_growth <- read_xlsx("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/project-gigas-conditioning-GL/data/sizes/B_2023POGS_small_seed_daily/B_sizes_09132024.xlsx")

# Heights from bag 2 for 07/05/2024 showing up as NAs for some reason when data imported
B_growth$length.mm <- as.numeric(B_growth$length.mm)
B_growth$width.mm <- as.numeric(B_growth$width.mm)
B_growth$height.mm <- as.numeric(B_growth$height.mm)
B_growth$date <- as.Date(B_growth$date)

B_growth <- B_growth %>% drop_na(length.mm, width.mm, height.mm)

# D survival
D_growth <- read_xlsx("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/project-gigas-conditioning-GL/data/sizes/D_2023POGS_small_seed_weekly/D_sizes_09132024.xlsx")
D_growth <- D_growth %>% drop_na(length.mm, width.mm, height.mm)
D_growth$date <- as.Date(D_growth$date)
```
## Histograms

### B
```{r}
B_growth %>%
  filter(date == "2024-09-13") %>%
  ggplot(aes(x = length.mm)) +
  geom_histogram(fill = "blue", color = "black") +
  labs(x = "Length (mm)", y = "Count") +
  theme_classic()

# B_growth$log_length <- log(B_growth$length.mm)
# hist(B_growth$log_length)

```

```{r}
B_growth %>%
  filter(date == "2024-09-13") %>%
ggplot(aes(x = height.mm)) +
  geom_histogram(fill = "blue", color = "black") +
  labs(x = "Height (mm)", y = "Count") +
  theme_classic()
# B_growth$log_height <- log(B_growth$height.mm)
# hist(B_growth$log_height)
```
```{r}
B_growth %>%
  filter(date == "2024-09-13") %>%
ggplot(aes(x = width.mm)) +
  geom_histogram(fill = "blue", color = "black") +
  labs(x = "Width (mm)", y = "Count") +
  theme_classic()
# B_growth$log_width <- log(B_growth$width.mm)
# hist(B_growth$log_width)
```
### D

```{r}
D_growth %>%
  filter(date == "2024-09-13") %>%
ggplot(aes(x = length.mm)) +
  geom_histogram(fill = "blue", color = "black") +
  labs(x = "Length (mm)", y = "Count") +
  theme_classic()
# D_growth$log_length <- log(D_growth$length.mm)
# hist(_growth$log_length)
```

```{r}
D_growth %>%
  filter(date == "2024-09-13") %>%
ggplot(aes(x = height.mm)) +
  geom_histogram(fill = "blue", color = "black") +
  labs(x = "Height (mm)", y = "Count") +
  theme_classic()
```

```{r}


D_growth %>%
  filter(date == "2024-09-13") %>%
ggplot(aes(x = width.mm)) +
  geom_histogram(fill = "blue", color = "black") +
  labs(x = "Width (mm)", y = "Count") +
  theme_classic()

```




## B comparisons

```{r}
ggplot(B_growth, aes(x=length.mm, y= height.mm))+
  geom_point()+
  theme_classic()+
  labs(x = "Length", y = "Height")+
  theme(axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        axis.text = element_text(size = 20))
```
```{r}
ggplot(B_growth, aes(x=length.mm, y= width.mm))+
  geom_point()+
  theme_classic()+
  labs(x = "Length", y = "Width")+
  theme(axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        axis.text = element_text(size = 20))
```
```{r}
ggplot(B_growth, aes(x=height.mm, y= width.mm))+
  geom_point()+
  theme_classic()+
  labs(x = "Height", y = "Width")+
  theme(axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        axis.text = element_text(size = 20))
```

## D comparisons

```{r}
ggplot(D_growth, aes(x=length.mm, y= height.mm))+
  geom_point()+
  theme_classic()+
  labs(x = "Length", y = "Height")+
  theme(axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        axis.text = element_text(size = 20))
```

```{r}
ggplot(D_growth, aes(x=length.mm, y= width.mm))+
  geom_point()+
  theme_classic()+
  labs(x = "Length", y = "Width")+
  theme(axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        axis.text = element_text(size = 20))

# Removing an outlier, I think it was an incorrect measurement
D_growth <- D_growth[D_growth$width.mm != 82, ]
```

```{r}
ggplot(D_growth, aes(x=width.mm, y= height.mm))+
  geom_point()+
  theme_classic()+
  labs(x = "Width", y = "Height")+
  theme(axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        axis.text = element_text(size = 20))
```

## D size correlations
### LM for correlation
```{r}
library(nlme)
library(lme4)
growth <- rbind(B_growth,D_growth)
growth_noNT <- growth[growth$tag_num != "NT", ]
growth_noNT$date_numeric <-  as.numeric(as.Date(growth_noNT$date))
growth$date_numeric <- as.numeric(as.Date(growth$date))


# Linear model with date as a continuous variable
# model <- lm(length.mm ~ width.mm + height.mm + date_numeric + effort/conditioning, data = growth_noNT)
# summary(model)



# lme model with nested random effects structure
model <- lmer(length.mm ~ width.mm + height.mm + effort/conditioning + date_numeric + (1 | bag_num/tag_num), data = growth_noNT)

summary(model)
library(car)
vif(lm(length.mm ~ effort/conditioning + date_numeric, data = growth_noNT))

```


```{r}
ggplot(growth, aes(x=length.mm, y= width.mm))+
  geom_point()+
  theme_classic()+
  labs(x = "Length", y = "Width")+
  theme(axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        axis.text = element_text(size = 20))
```

```{r}
plot(fitted(model), residuals(model), 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     main = "Residuals vs Fitted")
abline(h = 0, col = "red") 


qqnorm(residuals(model))
qqline(residuals(model), col = "red") 

```

```{r}
cooksd <- cooks.distance(model)

# Identify points with high Cook's distance (e.g., greater than 4/n where n is the number of observations)
outliers_cooks <- which(cooksd > 4 / nrow(D_growth))
print(D_growth[outliers_cooks, ]) 
```

```{r}
D_growth_PCA <- subset(D_growth, select = c(length.mm, width.mm, height.mm))

pca_result <- prcomp(D_growth_PCA, scale. = TRUE)

biplot(pca_result)


pca_data <- as.data.frame(pca_result$x)

# Create a scatter plot of the first two principal components
library(ggplot2)
ggplot(pca_data, aes(x = PC1, y = PC2)) +
  geom_point() +
  labs(title = "PCA: Length, Width, and Height", x = "PC1", y = "PC2") +
  theme_minimal()

pca_result$sdev^2 / sum(pca_result$sdev^2)

# Loadings (contribution of each variable to the principal components)
pca_result$rotation

# Scree plot
scree_values <- pca_result$sdev^2
plot(scree_values, type = "b", xlab = "Principal Component", ylab = "Eigenvalue", main = "Scree Plot")

```

## Predicting height and width from length

```{r}
model2 <- lm(log(height.mm)~length.mm+date_numeric, growth)
summary(model2)
plot(fitted(model2), residuals(model2), 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     main = "Residuals vs Fitted")
abline(h = 0, col = "red") 
library(car)

qqPlot(model2)

hist(residuals(model2))


bptest(model2)

# weighted model does not provide a better fit than first model (standard error increased, not much change in R squared)
# wt <- 1 / lm(abs(model2$residuals) ~ model2$fitted.values)$fitted.values^2
# wls_model2 <- lm( log(height.mm)~ length.mm+date_numeric, growth, weights=wt)
# summary(wls_model2)
# bptest(wls_model2)

```

```{r}
## Successful model!
model3 <- lm(sqrt(width.mm)~length.mm+date_numeric, growth)
summary(model3)

plot(fitted(model3), residuals(model3), 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     main = "Residuals vs Fitted")
abline(h = 0, col = "red") 

qqPlot(model3)

hist(residuals(model3))

bptest(model3)
# p = 0.03978

#made data more heteroskedastic somehow
# wt <- 1 / lm(abs(model3$residuals) ~ model3$fitted.values)$fitted.values^2
# wls_model3 <- lm(sqrt(width.mm)~ length.mm+date_numeric, growth, weights=wt)
# summary(wls_model3)

```
### Tried to see if subsetting improved anything
```{r}
day1 <- subset(growth, date_numeric == 19884)

ggplot(day1, aes(x=length.mm, y= height.mm))+
  geom_point()+
  theme_classic()+
  labs(x = "Length", y = "Width")+
  theme(axis.title.x = element_text(size = 20),
        axis.title.y = element_text(size = 20),
        axis.text = element_text(size = 20))

model4 <- lm(sqrt(width.mm)~length.mm, day1)
summary(model4)

plot(fitted(model4), residuals(model4), 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     main = "Residuals vs Fitted")
abline(h = 0, col = "red") 

qqPlot(model4)

hist(residuals(model4))

bptest(model4)

## Subsetting made it pass the bp test, fit not as good though
model5 <- lm(log(height.mm)~length.mm, day1)
summary(model5)

plot(fitted(model5), residuals(model5), 
     xlab = "Fitted Values", 
     ylab = "Residuals", 
     main = "Residuals vs Fitted")
abline(h = 0, col = "red") 

qqPlot(model5)

hist(residuals(model5))

bptest(model5)

```


```{r}
growth$volume <- (4/3) * pi * (growth$length.mm/2) * (growth$width.mm/2) * (growth$height.mm/2)

growth$conditioning <- gsub("weekly", "treated", growth$conditioning)
growth$conditioning <- gsub("daily", "treated", growth$conditioning)

```


### Modeling looking for effect of effort and conditioning on volume (measurement date and bag number as random effects)
```{r}
model <- lmer(log(volume) ~  effort/conditioning + (1 | date_numeric/bag_num), data = growth)
summary(model)
anova(model)

qqPlot(residuals(model))
plot(fitted(model), residuals(model))
abline(h = 0, col = "red") 

```



