---
title: "Survival_analysis"
output: html_document
date: "2024-06-26"
---

### Load libraries
```{r}
library(readxl)
library(tidyverse)
library(ggplot2)

```

### Load Data
```{r}
# B survival
B_survival <- read_excel("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/project-gigas-conditioning-GL/data/survival/Westcott/B_survival_07082024.xlsx")


# D survival
D_survival <- read_excel("/Users/graceleuchtenberger/Library/Mobile Documents/com~apple~CloudDocs/Documents/project-gigas-conditioning-GL/data/survival/Westcott/D_survival_07082024.xlsx")

```

### Combine data, reup it
```{r}
means_B_live <- B_survival %>%
  group_by(conditioning, date) %>%
  summarise(mean_survival = mean(alive_num),
            std_error = sd(alive_num)/sqrt(length(alive_num)),
            .groups = 'drop')

means_D_live <- D_survival %>%
  group_by(conditioning, date) %>%
  summarise(mean_survival = mean(alive_num),
            std_error = sd(alive_num)/sqrt(length(alive_num)),
            .groups = 'drop')

means_live <- rbind(means_B_live, means_D_live)

means_live$effort <- c("B","B","B","B","B","B","D","D","D","D","D","D")
means_live$conditioning <- c("d_control","d_control","d_control","daily","daily","daily","w_control","w_control","w_control","weekly","weekly","weekly")

```

### Stats


```{r}
ggplot(means_live, aes(x = date, y = mean_survival, group = effort, color = conditioning)) +
   geom_point(size=3) +
  labs(x = "Date",
       y = "Mean live oysters per bag") +
  scale_color_manual(labels = c("Daily Control", "Daily", "Weekly Control", "Weekly"), values = c("blue", "red", "green", "purple"))+
  labs(color = "Conditioning")+
  geom_errorbar(aes(ymin=mean_survival-std_error, ymax=mean_survival+std_error), width=.2,
                 position=position_dodge(0.05))+
  theme_classic()
```
```{r}

ggplot(D_survival, aes(x = date, y = alive_num, group = effort, color = conditioning)) +
   geom_jitter(width = 10, height = 0, size=3) +
  labs(x = "Date",
       y = "Mean live oysters per bag") +
  scale_color_manual(labels = c("Control", "Weekly"), values = c("green","purple"))+
  labs(color = "Conditioning")+
  theme_classic()+
  ylim(0,120)

```

```{r}

ggplot(B_survival, aes(x = date, y = alive_num, group = effort, color = conditioning)) +
   geom_jitter(width = 10, height = 0,size=3) +
  labs(x = "Date",
       y = "Mean live oysters per bag") +
  scale_color_manual(labels = c("Control", "Daily"), values = c("blue","red"))+
  labs(color = "Conditioning")+
  theme_classic()+
  ylim(0,55)

```

```{r}
ggplot(B_survival, aes(x=date,y=dead, color=conditioning))+
  geom_jitter(width = 0.2, height = 0.2, size = 3) +
  theme_classic()+
  ylab("Dead oysters found")+
  xlab("Date")+
  ylim(-1,2)


```
```{r}
ggplot(D_survival, aes(x=date, y=dead, color=conditioning))+
  geom_jitter(width = 0.2, height = 0.2, size = 3) +
  theme_classic()+
  ylab("Dead oysters found")+
  xlab("Date")+
  ylim(-1,2)

```
### Cumulative survival
```{r}
B_survival <- B_survival %>%
  group_by(conditioning, bag_num) %>%
  arrange(date)%>%
  mutate(cumulative_deaths = cumsum(dead)) %>%
  ungroup()

D_survival <- D_survival %>%
  group_by(conditioning, bag_num) %>%
  arrange(date)%>%
  mutate(cumulative_deaths = cumsum(dead)) %>%
  ungroup()

```


```{r}
ggplot(B_survival, aes(x=date, y=cumulative_deaths, color=conditioning))+
  geom_jitter(width = 0.2, height = 0.1, size = 3) +
  theme_classic()+
  ylab("Dead oysters found")+
  xlab("Date")+
  labs(color = "Conditioning")+
  scale_color_manual(labels = c("Control", "Daily"),values = c("blue", "red"))
  ylim(-1,2)
```
```{r}
ggplot(D_survival, aes(x=date, y=cumulative_deaths, color=conditioning))+
  geom_jitter(width = 0.2, height = 0.2, size = 3) +
  theme_classic()+
  ylab("Dead oysters found")+
  xlab("Date")+
  labs(color= "Conditioning")+
  scale_color_manual(labels = c("Control", "Weekly"),values = c("green", "purple"))+
  ylim(-1,2.5)
```
```


